microapp:
  microId: common-bff

server:
  port: 9100

# Core Services url
service:
  authnz:
    protocol: http://
    host: 127.0.0.1
    port: ${AUTHNZ_PORT::8081}
    uri: /v1  
    url: ${service.authnz.protocol}${service.authnz.host}${service.authnz.port}${service.authnz.uri}
     
  mdmUserManagement:
     protocol: http://
     host: ${USER_MANAGEMENT_HOST:127.0.0.1}
     port: ${USER_MANAGEMENT_PORT::8090}    
     objects_uri: /objects/
     users_uri: /users/
     roles_uri: /roles/
     version : /v1
     users_url: ${service.mdmUserManagement.protocol}${service.mdmUserManagement.host}${service.mdmUserManagement.port}${service.mdmUserManagement.version}${service.mdmUserManagement.users_uri}
     objects_url: ${service.mdmUserManagement.protocol}${service.mdmUserManagement.host}${service.mdmUserManagement.port}${service.mdmUserManagement.version}${service.mdmUserManagement.objects_uri}
     roles_url: ${service.mdmUserManagement.protocol}${service.mdmUserManagement.host}${service.mdmUserManagement.port}${service.mdmUserManagement.version}${service.mdmUserManagement.roles_uri}
     mdm_user_mgmt_url: ${service.mdmUserManagement.protocol}${service.mdmUserManagement.host}${service.mdmUserManagement.port}${service.mdmUserManagement.version}

  lookUpNotepadCommandmentService:
      host: 127.0.0.1
      port: ${LOOKUP_NOTEPAD_COMMANDMENT_PORT::9096}
      version: /v1
      lookUp_uri: /mdm/
      look_up_url: ${service.mdmUserManagement.protocol}${service.lookUpNotepadCommandmentService.host}${service.lookUpNotepadCommandmentService.port}${service.lookUpNotepadCommandmentService.version}${service.lookUpNotepadCommandmentService.lookUp_uri}
  
  branchService:    
      host: 127.0.0.1
      port: ${BRANCH_PORT::9097}     
      version: /v1/
      branch_uri: branches/
      geo_uri: geodetails/
      branch_url: ${service.mdmUserManagement.protocol}${service.branchService.host}${service.branchService.port}${service.branchService.version}${service.branchService.branch_uri}
      geo_url: ${service.mdmUserManagement.protocol}${service.branchService.host}${service.branchService.port}${service.branchService.version}${service.branchService.geo_uri}

# Redis cache configuration
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
app:           
  redis:
    host: ${REDIS_HOST:master.dev-private-propel-i-redis-ec.97ggud.aps1.cache.amazonaws.com}
    password: ${REDIS_PASSWORD:XM2tK7PLaD3FV6NxATBt}
    port: ${REDIS_PORT:6379}
ad:
  service:
    url: http://webs.safexpress.com:8081/SafeApi/webresources/sale_force_login 
    
# timeout in milliseconds
security:
  session:
    timeout: 18000000

message:
  success: Success