microapp:
  microId: common-bff

server:
  port: 80

# Core Services url
service:
  authnz:
    host: ${AUTHNZ_HOST:127.0.0.1}
    port: ${AUTHNZ_PORT:7000}  
    uri: /v1  
     
  mdmUserManagement:
     protocol: http://
     host: ${USER_MANAGEMENT_HOST:127.0.0.1}
     port: ${USER_MANAGEMENT_PORT::9095}
     objects_uri: /objects/
     users_uri: /users/
     roles_uri: /roles/
     version : /v1
     users_url: ${service.mdmUserManagement.protocol}${service.mdmUserManagement.host}${service.mdmUserManagement.port}${service.mdmUserManagement.version}${service.mdmUserManagement.users_uri}
     objects_url: ${service.mdmUserManagement.protocol}${service.mdmUserManagement.host}${service.mdmUserManagement.port}${service.mdmUserManagement.version}${service.mdmUserManagement.objects_uri}
     roles_url: ${service.mdmUserManagement.protocol}${service.mdmUserManagement.host}${service.mdmUserManagement.port}${service.mdmUserManagement.version}${service.mdmUserManagement.roles_uri}
     mdm_user_mgmt_url: ${service.mdmUserManagement.protocol}${service.mdmUserManagement.host}${service.mdmUserManagement.port}${service.mdmUserManagement.version}

  lookUpNotepadCommandmentService:
      host: ${LOOKUP_NOTEPAD_COMMANDMENT_HOST:127.0.0.1}
      port: ${LOOKUP_NOTEPAD_COMMANDMENT_PORT::9096}
      version: /v1
      lookUp_uri: /mdm/
      look_up_url: ${service.mdmUserManagement.protocol}${service.lookUpNotepadCommandmentService.host}${service.lookUpNotepadCommandmentService.port}${service.lookUpNotepadCommandmentService.version}${service.lookUpNotepadCommandmentService.lookUp_uri}
  branchService:
      host: ${BRANCH_HOST:127.0.0.1}
      port: ${BRANCH_PORT::9001}
      version: /v1/
      branch_uri: branches/
      branch_url: ${service.mdmUserManagement.protocol}${service.branchService.host}${service.branchService.port}${service.branchService.version}${service.branchService.branch_uri}

        # Redis cache configuration
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
app:           
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    password: ${REDIS_PASSWORD:admin}
    port: ${REDIS_PORT:6379}
ad:
  service:
    url: http://webs.safexpress.com:8081/SafeApi/webresources/sale_force_login 
    
# timeout in milliseconds
security:
  session:
    timeout: 18000000

message:
  success: Success