microapp: 
  microId:user_management_bff  
 
server: 
  port: 80 
 
# Core Services url 
service: 
  authnz: 
    service_name: /authnz-service     
    version: /v1   
    url: ${service.authnz.service_name}${service.authnz.version} 
      
  mdmUserManagement: 
    service_name: mdm-usermanagement-service 
    objects_uri: /objects/ 
    users_uri: /users/ 
    roles_uri: /roles/ 
    version : /v1 
    users_url: ${service.mdmUserManagement.service_name}${service.mdmUserManagement.version}${service.mdmUserManagement.users_uri} 
    objects_url: ${service.mdmUserManagement.service_name}${service.mdmUserManagement.version}${service.mdmUserManagement.objects_uri} 
    roles_url: ${service.mdmUserManagement.service_name}${service.mdmUserManagement.version}${service.mdmUserManagement.roles_uri} 
    mdm_user_mgmt_url: ${service.mdmUserManagement.service_name}${service.mdmUserManagement.version} 
   
  lookUpNotepadCommandmentService: 
    service_name: mdmcommandmentnotepadlookupservice 
    version: /v1 
    lookUp_uri: /mdm/ 
    look_up_url: ${service.lookUpNotepadCommandmentService.service_name}${service.lookUpNotepadCommandmentService.version}${service.lookUpNotepadCommandmentService.lookUp_uri} 
   
  branchService: 
    service_name: mdmgeozmbranchservice 
    version: /v1/ 
    branch_uri: branches/ 
    geo_uri: geodetails/ 
    branch_url: ${service.branchService.service_name}${service.branchService.version}${service.branchService.branch_uri} 
    geo_url: ${service.branchService.service_name}${service.branchService.version}${service.branchService.geo_uri} 
 
 # Redis cache configuration 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
app:            
  redis: 
    host: ${REDIS_HOST:master.dev-private-propel-i-redis-ec.97ggud.aps1.cache.amazonaws.com} 
    password: ${REDIS_PASSWORD:XM2tK7PLaD3FV6NxATBt} 
    port: ${REDIS_PORT:6379} 
ad: 
  service: 
    url: http://webs.safexpress.com:8081/SafeApi/webresources/sale_force_login  
     
# timeout in milliseconds 
security: 
  session: 
    timeout: 18000000 
 
message: 
  success: Success 