apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: commonbff
  namespace: dev
spec:
  destination:
    name: commonbff
  corsPolicy:
    allowOrigin:
      - http://*.ap-south-1.elb.amazonaws.com
    allowMethods:
      - POST
      - GET
      - OPTIONS
    allowHeaders:
      - content-type
    exposeHeaders:
      - x-custom-header
    maxAge: 300s
    allowCredentials: true